# Generated by Django 2.0.1 on 2018-01-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelyveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargoName', models.CharField(max_length=200)),
                ('shippingCost', models.FloatField()),
                ('weight', models.FloatField()),
                ('scope', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcedureName', models.CharField(max_length=200)),
                ('OurContractInfo', models.CharField(max_length=200)),
                ('YourContractInfo', models.CharField(max_length=200)),
            ],
        ),
    ]
