# Generated by Django 2.0.1 on 2018-01-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'), 
    ]

    operations = [
        migrations.RenameField('ProcedureInfo', 'ProcedureName', 'procedureName'),
        migrations.RenameField('ProcedureInfo', 'OurContractInfo', 'ourContractInfo'),
		migrations.RenameField('ProcedureInfo', 'YourContractInfo', 'yourContractInfo'),
		migrations.RemoveField('DelyveryInfo','weight'),
		migrations.RemoveField('DelyveryInfo','scope'),
		migrations.AddField('DelyveryInfo','destiny',models.CharField(max_length=200)),
    ]
